deployment:
  tasks:
    - composer install --optimize-autoloader --no-dev
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan route:trans:cache
    - php artisan storage:link
    - php artisan migrate:fresh --seed

